### ISSUE TITLE
Extending to UF Sparse Matrix collection

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaSparse/MatrixMarket.jl#1]
What would it take to extend this to Tim Davis's collection?
It looks like we could just 
`curl https://www.cise.ufl.edu/research/sparse/MM/$MATGROUP/$MATNAME.tar.gz; tar xzf $MATNAME.tar.gz` and then use this package to read it. 

Or would it be better use the mat formats and `Mat.jl`?

**Comment by tkonolige** [comment]
Looks like [https://github.com/weijianzhang/MatrixDepot.jl](https://github.com/weijianzhang/MatrixDepot.jl) has this covered.
