### ISSUE TITLE
parsefloat or parseint?

### ISSUE THREAD

**Issue by dpo** [JuliaSparse/MatrixMarket.jl#10]
I'm in the process of converting the `parseint`s to `parse(Int, ...)` for compatibility with Julia nightly. Shouldn't this one have been a `parseint`: https://github.com/JuliaSparse/MatrixMarket.jl/blob/master/src/MatrixMarket.jl#L67 ?

**Comment by ScottPJones** [comment]
I also just noticed the same problem, and was about to add a PR when I discovered this issue.
The line seems to be from @jakebolewski
