### ISSUE TITLE
Export mmread?

### ISSUE THREAD

**Issue by dpo** [JuliaSparse/MatrixMarket.jl#3]
Should the `MatrixMarket` module export the `mmread` function?

**Comment by jakebolewski** [comment]
My preference would be to use an existing method in Base and not export the overloaded method, `MatrixMarket.readall(filename)`.  That way you get to reuse an existing verb.

**Comment by dpo** [comment]
That makes sense to me, although people used to the MatrixMarket format are also used to the name `mmread`. That's what it's been called in C, Fortran and Matlab for ages. Perhaps there could be an alias?

**Comment by tkonolige** [comment]
#15 closes this

**Comment by timholy** [comment]
Would arguably be better to use the infrastructure in [FileIO](https://github.com/JuliaIO/FileIO.jl), esp. if `mtx` format has magic bytes.
