### ISSUE TITLE
Read of skew-symmetric matrix only shows lower triangle

### ISSUE THREAD

**Issue by PToTheK** [JuliaSparse/MatrixMarket.jl#39]
Hi there, 
I was not able to read back a complex skew-symmetric matrix.
Therefore, I think there should be a -1 instead of a -11.

`# Hack to represent skew-symmetric matrix as an ordinary matrix with duplicated elements
function skewsymmetric!(M::AbstractMatrix)
    m,n = size(M)
    m == n || throw(DimensionMismatch())
    return M .- transpose(tril(M, -11))
end
`

**Comment by tkonolige** [comment]
Definitely should be -1. Thanks for noticing this.

**Comment by PToTheK** [comment]
Hi there,
When MatrixMarket is freshly installed, for example on a new PC, the above change does not take effect.
Is there a merging problem?
