### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by rasmushenningsson** [JuliaSparse/MatrixMarket.jl#48]
The last release is from 2019 and the package has been improved since then.
(In particular Compat, is no longer a dependency.)

**Comment by yuehhua** [comment]
It seems that v0.4.0 is not tagged. Could someone tag it?

**Comment by tkonolige** [comment]
@amontoison Seems like tag bot is not working?

**Comment by rasmushenningsson** [comment]
There was hickup in the Julia Registrator CI that prevented the new version from being released.
That's been solved by @DilumAluthge, so now the new version is available and tagged.
